### PR TITLE
listen page

### PR DESCRIPTION
**Pull request by ken333135**

### CODE REVIEW

**Review by 0xOptimism — APPROVED** [review]
LGTM, should we discuss on linting rules before the project got too big?

**Comment by roseja** [comment]
> 

I agree with this... my IDE is using double quotes, but I see a lot of single quotes. Is there a linter we can use to standardize them all?

**Comment by 0xOptimism** [comment]
@roseja @ken333135 @tony-stark-dex What do you guys think of the airbnb linting rules? a bit of setup but maybe it can be nice to keep consistency over the repo https://gist.github.com/EliEladElrom/54c5046cf21877824d1bc38d5dd33d81

**Comment by roseja** [comment]
> @roseja @ken333135 @tony-stark-dex What do you guys think of the airbnb linting rules? a bit of setup but maybe it can be nice to keep consistency over the repo https://gist.github.com/EliEladElrom/54c5046cf21877824d1bc38d5dd33d81

Yeah, I love that idea!

**Pull request merged**
